
<div class="w-xxxx-12">
    <div class="content">
        <?=getCatalogVitrina('nuevos-productos')?>
    </div>
</div>


<div class="w-xxxx-12">
    <div class="content">
        <?=getCarrusel('prueba-1')?>
    </div>
</div>

<div class="w-xxxx-12">
    <div class="content">
        <?=getBloqueCMS("demo")?>
    </div>
</div>

<div class="w-xxxx-12">
    <div class="content">
        <?=getSlider('prueba-1')?>
    </div>
</div>